#!/bin/bash
#
# Local GPU Detection and Configuration Script
# Detects your GPU and suggests optimal compilation settings
#

echo "=========================================="
echo "  Local GPU Detection & Setup"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# Check if NVIDIA GPU is available
# ============================================================================

echo -e "${BLUE}Step 1: Checking for NVIDIA GPU...${NC}"
if ! command -v nvidia-smi &> /dev/null; then
    echo -e "${RED}✗ nvidia-smi not found${NC}"
    echo ""
    echo "This could mean:"
    echo "  1. No NVIDIA GPU in system"
    echo "  2. NVIDIA drivers not installed"
    echo "  3. WSL2 GPU passthrough not configured"
    echo ""
    echo "For WSL2 GPU support, see:"
    echo "  https://docs.nvidia.com/cuda/wsl-user-guide/"
    exit 1
fi

echo -e "${GREEN}✓ nvidia-smi found${NC}"
echo ""

# ============================================================================
# Get GPU Information
# ============================================================================

echo -e "${BLUE}Step 2: Detecting GPU...${NC}"
nvidia-smi --query-gpu=name,compute_cap,memory.total --format=csv,noheader

GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
COMPUTE_CAP=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | head -1)
MEMORY_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)

echo ""
echo -e "${GREEN}GPU Detected:${NC}"
echo "  Name: $GPU_NAME"
echo "  Compute Capability: $COMPUTE_CAP"
echo "  Memory: ${MEMORY_MB} MB"
echo ""

# ============================================================================
# Determine Architecture Flag
# ============================================================================

echo -e "${BLUE}Step 3: Determining compilation settings...${NC}"

# Remove decimal point from compute capability
COMPUTE_CAP_CLEAN=$(echo $COMPUTE_CAP | tr -d '.')

# Map to architecture
case "$COMPUTE_CAP_CLEAN" in
    89)
        ARCH_FLAG="sm_89"
        GPU_FAMILY="Ada Lovelace (RTX 40-series)"
        PEAK_TFLOPS="40-80"  # Approximate
        PEAK_BANDWIDTH="600-1000"
        ;;
    86)
        ARCH_FLAG="sm_86"
        GPU_FAMILY="Ampere (RTX 30-series)"
        PEAK_TFLOPS="20-40"
        PEAK_BANDWIDTH="600-900"
        ;;
    75)
        ARCH_FLAG="sm_75"
        GPU_FAMILY="Turing (RTX 20-series, GTX 16-series)"
        PEAK_TFLOPS="10-20"
        PEAK_BANDWIDTH="400-600"
        ;;
    70)
        ARCH_FLAG="sm_70"
        GPU_FAMILY="Volta (V100, Titan V)"
        PEAK_TFLOPS="7-15"
        PEAK_BANDWIDTH="900"
        ;;
    61)
        ARCH_FLAG="sm_61"
        GPU_FAMILY="Pascal (GTX 10-series)"
        PEAK_TFLOPS="8-12"
        PEAK_BANDWIDTH="300-500"
        ;;
    *)
        ARCH_FLAG="sm_${COMPUTE_CAP_CLEAN}"
        GPU_FAMILY="Unknown"
        PEAK_TFLOPS="Unknown"
        PEAK_BANDWIDTH="Unknown"
        ;;
esac

echo -e "${GREEN}Architecture Settings:${NC}"
echo "  GPU Family: $GPU_FAMILY"
echo "  Architecture Flag: -arch=$ARCH_FLAG"
echo "  Estimated Peak TFLOPS: $PEAK_TFLOPS"
echo "  Estimated Bandwidth (GB/s): $PEAK_BANDWIDTH"
echo ""

# ============================================================================
# Check CUDA Toolkit
# ============================================================================

echo -e "${BLUE}Step 4: Checking CUDA toolkit...${NC}"

if command -v nvcc &> /dev/null; then
    NVCC_VERSION=$(nvcc --version | grep "release" | awk '{print $5}' | cut -d',' -f1)
    echo -e "${GREEN}✓ CUDA toolkit installed${NC}"
    echo "  Version: $NVCC_VERSION"
    echo "  Location: $(which nvcc)"
else
    echo -e "${RED}✗ nvcc not found${NC}"
    echo ""
    echo "You need to install CUDA toolkit in WSL2."
    echo ""
    echo "Installation steps:"
    echo "  1. wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.1-1_all.deb"
    echo "  2. sudo dpkg -i cuda-keyring_1.1-1_all.deb"
    echo "  3. sudo apt-get update"
    echo "  4. sudo apt-get -y install cuda-toolkit-12-2"
    echo ""
    echo "Or visit: https://developer.nvidia.com/cuda-downloads"
    exit 1
fi

echo ""

# ============================================================================
# Generate Configuration
# ============================================================================

echo -e "${BLUE}Step 5: Generating local configuration...${NC}"

# Create Makefile.local
cat > Makefile.local << EOF
# Local GPU Configuration
# Auto-generated by check_local_gpu.sh
# GPU: $GPU_NAME
# Compute Capability: $COMPUTE_CAP

NVCC = nvcc
NVCC_FLAGS = -O3 -arch=$ARCH_FLAG -Xcompiler -Wall
NVCC_FLAGS_DEBUG = -g -G -arch=$ARCH_FLAG -Xcompiler -Wall
LIBS = -lcublas -lcusparse

# Source files
SRC_DIR = src
UTILS = \$(SRC_DIR)/utils.cu

# Fast local testing targets
.PHONY: local-quick local-test local-debug

# Quick build for iteration
local-quick: \$(SRC_DIR)/nmf_dense_gpu_v1_naive.cu \$(UTILS)
	\$(NVCC) \$(NVCC_FLAGS) \$^ -o nmf_local \$(LIBS)
	@echo "Built nmf_local for quick testing"

# Debug build
local-debug: \$(SRC_DIR)/nmf_dense_gpu_v1_naive.cu \$(UTILS)
	\$(NVCC) \$(NVCC_FLAGS_DEBUG) \$^ -o nmf_local_debug \$(LIBS)
	@echo "Built nmf_local_debug with debug symbols"

# Quick test (small size)
local-test: local-quick
	./nmf_local 100 10 20
	@echo ""
	@echo "Quick test complete!"

# Profile locally
local-profile: local-quick
	nsys profile --stats=true ./nmf_local 1000 20 10

clean-local:
	rm -f nmf_local nmf_local_debug
EOF

echo -e "${GREEN}✓ Created Makefile.local${NC}"

# Create GPU config for Python scripts
cat > gpu_config.py << EOF
# Local GPU Configuration
# Auto-generated by check_local_gpu.sh

GPU_NAME = "$GPU_NAME"
COMPUTE_CAPABILITY = "$COMPUTE_CAP"
ARCHITECTURE = "$ARCH_FLAG"
GPU_FAMILY = "$GPU_FAMILY"

# Performance estimates (adjust after benchmarking)
PEAK_TFLOPS = $PEAK_TFLOPS  # Adjust based on actual GPU
PEAK_BANDWIDTH_GBS = $PEAK_BANDWIDTH  # GB/s

# For roofline analysis
if isinstance(PEAK_TFLOPS, str):
    # Take middle of range
    PEAK_TFLOPS = float(PEAK_TFLOPS.split('-')[0])
if isinstance(PEAK_BANDWIDTH_GBS, str):
    PEAK_BANDWIDTH_GBS = float(PEAK_BANDWIDTH_GBS.split('-')[0])

PEAK_FLOPS = PEAK_TFLOPS * 1e12
PEAK_BANDWIDTH = PEAK_BANDWIDTH_GBS * 1e9
EOF

echo -e "${GREEN}✓ Created gpu_config.py${NC}"
echo ""

# ============================================================================
# Summary and Next Steps
# ============================================================================

echo -e "${GREEN}=========================================="
echo "  Setup Complete!"
echo "==========================================${NC}"
echo ""
echo "Your GPU is ready for local development!"
echo ""
echo -e "${YELLOW}Quick Start Commands:${NC}"
echo ""
echo "  # Fast build and test"
echo "  make -f Makefile.local local-test"
echo ""
echo "  # Full build all levels"
echo "  make NVCC_FLAGS=\"-O3 -arch=$ARCH_FLAG -Xcompiler -Wall\""
echo ""
echo "  # Debug build"
echo "  make -f Makefile.local local-debug"
echo ""
echo -e "${YELLOW}Update Main Makefile:${NC}"
echo ""
echo "  Edit Makefile and change:"
echo "  NVCC_FLAGS = -O3 -arch=$ARCH_FLAG -Xcompiler -Wall"
echo ""
echo -e "${YELLOW}For Roofline Analysis:${NC}"
echo ""
echo "  python3 scripts/roofline_analysis.py \\"
echo "    --gpu-config gpu_config.py \\"
echo "    --size 1000 --rank 20"
echo ""
echo "Files created:"
echo "  ✓ Makefile.local (local development)"
echo "  ✓ gpu_config.py (for Python scripts)"
echo ""
echo -e "${GREEN}Ready to code! Try: make -f Makefile.local local-test${NC}"
echo ""
